name: Update Assets

on:
    push:
        branches: ['reactify']

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.10.x]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - run: pip install -r scripts/requirements.txt
      name: Install the dependencies
      shell: bash
    - run: python scripts/update_assets.py
      name: Update assets
      shell: bash

    - name: Set Username and Email
      run : |
        git config user.name github-actions
        git config user.email github-actions@github.com
      shell: bash
    - name: Check for changes and commit
      run : |
        git add .
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Updating Assets by github-actions"
          git push
        fi
      shell: bash
    
